version: "3.8"
networks:
  tempo:

volumes:
  tempo: 

services:
  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo:/var/tempo

  tempo1:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./tempo:/var/tempo
    networks:
      tempo:
        aliases:
          - tempo
    ports:
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "3100:3100"
    depends_on:
      - init

  tempo2:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./tempo:/var/tempo
    networks:
      tempo:
        aliases:
          - tempo
    depends_on:
      - init
  
  tempo3:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./tempo:/var/tempo
    networks:
      tempo:
        aliases:
          - tempo
    depends_on:
      - init